Generalise wkt normalisation boundary check for any boundary
digital-land/pipeline pull request #135
Opened 2023-09-14 15:32 UTC by CarlosCoelhoSL

Trello ticket: https://trello.com/c/tyDiJ0yi/453-investigate-and-detect-brownfield-land-sites-that-fall-outside-their-lpa-geometry

# The problem

In order to detect whether brownfield land is in the wrong place, there must be a process that can accept an LPA boundary and check whether the point lies within that boundary. Currently, the normalisation process in the wkt class verifies that the wkt lies within a hardcoded bounding box of England, so this can be modified to accept a custom boundary.

# What's changed

This PR adds an optional input to the normalisation function , `boundary`, which then is used to validate that the wkt lies within this custom boundary. The boundary must of a wkt of type Polygon or MultiPolygon. If no boundary is input into the function, it will use a default boundary, this being the 'within England' bounding box.

Notes:

While investigating this area of the code, it was found that the 'within England' bounding box used when judging WGS84 and OSGB crs were different from each other. In order to create a unified idea of 'within England', the default boundary used here is the intersection of the two original bounding boxes

2023-09-14 15:46 UTC, GeorgeGoodall approved these changes
LGTM

2023-09-15 10:18 UTC, eveleighoj requested changes

2023-09-23 08:18 UTC, hyperoceanic commented
We should ensure we update the documentation materials when we change the application logic.

2023-09-28 09:26 UTC, morgan-sl approved these changes
code looks ok.

2023-10-02 12:38 UTC, eveleighoj commented on digital_land/datatype/wkt.py
>  from shapely.geometry import MultiPolygon
Looks good just update it with the bounds after the NSIP stuff.

2023-10-02 15:48 UTC, merged